apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: terraform-rhcs-rosa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-rhcs-rosa-test/terraform-rhcs-rosa@sha256:bd1692edf3215b01adac42f39373ac7ca37340a2cad6a8f80c49e073c3ee7927
        name: container-image
        resources: {}
status: {}
