apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: terraform-rhcs-rosa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-rhcs-rosa-test/terraform-rhcs-rosa@sha256:952f3269316f11afafa2db779c60c9d68909ead40234b7e7d976fb7b57ce9248
        name: container-image
        resources: {}
status: {}
